-- Migration: Add ai_recommendation column to the events table
-- This column stores actionable cost-saving insights generated by AI.

ALTER TABLE public.events ADD COLUMN IF NOT EXISTS ai_recommendation text;
