/**
 * Static fallback model list.
 * Used only when the OpenRouter API is unreachable.
 * Pricing figures are approximate and based on public docs (May 2025).
 * All prices are USD per single token.
 */

import type { AIModel } from "@/types/ai-model";

export const FALLBACK_MODELS: AIModel[] = [
  // ── OpenAI ──────────────────────────────────────────────────────────────
  {
    modelId: "openai/gpt-4o",
    displayName: "GPT-4o",
    provider: "openai",
    inputPrice: 0.0000025,
    outputPrice: 0.00001,
    contextLength: 128000,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: false,
  },
  {
    modelId: "openai/gpt-4o-mini",
    displayName: "GPT-4o mini",
    provider: "openai",
    inputPrice: 0.00000015,
    outputPrice: 0.0000006,
    contextLength: 128000,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: false,
  },
  {
    modelId: "openai/o3-mini",
    displayName: "o3 mini",
    provider: "openai",
    inputPrice: 0.0000011,
    outputPrice: 0.0000044,
    contextLength: 200000,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: true,
  },
  {
    modelId: "openai/o4-mini",
    displayName: "o4 mini",
    provider: "openai",
    inputPrice: 0.0000011,
    outputPrice: 0.0000044,
    contextLength: 200000,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
  },
  // ── Anthropic ───────────────────────────────────────────────────────────
  {
    modelId: "anthropic/claude-opus-4-5",
    displayName: "Claude Opus 4.5",
    provider: "anthropic",
    inputPrice: 0.000015,
    outputPrice: 0.000075,
    contextLength: 200000,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: false,
  },
  {
    modelId: "anthropic/claude-sonnet-4-5",
    displayName: "Claude Sonnet 4.5",
    provider: "anthropic",
    inputPrice: 0.000003,
    outputPrice: 0.000015,
    contextLength: 200000,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: false,
  },
  {
    modelId: "anthropic/claude-haiku-3-5",
    displayName: "Claude Haiku 3.5",
    provider: "anthropic",
    inputPrice: 0.0000008,
    outputPrice: 0.000004,
    contextLength: 200000,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: false,
  },
  // ── Google ──────────────────────────────────────────────────────────────
  {
    modelId: "google/gemini-2.5-pro-preview",
    displayName: "Gemini 2.5 Pro",
    provider: "google",
    inputPrice: 0.00000125,
    outputPrice: 0.00001,
    contextLength: 1048576,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
  },
  {
    modelId: "google/gemini-2.5-flash-preview",
    displayName: "Gemini 2.5 Flash",
    provider: "google",
    inputPrice: 0.00000015,
    outputPrice: 0.0000006,
    contextLength: 1048576,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
  },
  {
    modelId: "google/gemini-2.0-flash-001",
    displayName: "Gemini 2.0 Flash",
    provider: "google",
    inputPrice: 0.0000001,
    outputPrice: 0.0000004,
    contextLength: 1048576,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: false,
  },
  // ── xAI ─────────────────────────────────────────────────────────────────
  {
    modelId: "x-ai/grok-build-0.1",
    displayName: "Grok Build 0.1",
    provider: "x-ai",
    inputPrice: 0.000001,
    outputPrice: 0.000002,
    contextLength: 256000,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: true,
  },
  {
    modelId: "x-ai/grok-2-1212",
    displayName: "Grok 2",
    provider: "x-ai",
    inputPrice: 0.000002,
    outputPrice: 0.00001,
    contextLength: 128000,
    supportsTools: true,
    supportsVision: true,
    supportsReasoning: false,
  },
  // ── DeepSeek ────────────────────────────────────────────────────────────
  {
    modelId: "deepseek/deepseek-chat",
    displayName: "DeepSeek V3",
    provider: "deepseek",
    inputPrice: 0.00000027,
    outputPrice: 0.0000011,
    contextLength: 64000,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: false,
  },
  {
    modelId: "deepseek/deepseek-reasoner",
    displayName: "DeepSeek R1",
    provider: "deepseek",
    inputPrice: 0.00000055,
    outputPrice: 0.00000219,
    contextLength: 64000,
    supportsTools: false,
    supportsVision: false,
    supportsReasoning: true,
  },
  // ── Qwen ────────────────────────────────────────────────────────────────
  {
    modelId: "qwen/qwen3-235b-a22b",
    displayName: "Qwen3 235B A22B",
    provider: "qwen",
    inputPrice: 0.00000022,
    outputPrice: 0.00000088,
    contextLength: 41000,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: true,
  },
  {
    modelId: "qwen/qwen3-32b",
    displayName: "Qwen3 32B",
    provider: "qwen",
    inputPrice: 0.00000010,
    outputPrice: 0.00000040,
    contextLength: 41000,
    supportsTools: true,
    supportsVision: false,
    supportsReasoning: true,
  },
];
